name = "Lc2ppiKSemileptonicModelLHCb"
uuid = "2be14d12-1226-44dd-959e-4e18ae37578d"
authors = ["Mikhail Mikhasenko <mikhail.mikhasenko@cern.ch>"]
version = "0.4.1"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
ThreeBodyDecays = "e6563dab-9ca1-5843-bde3-2ccf38d63843"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
BenchmarkTools = "1.4.0"
Corpuscles = "2.1.1"
DataFrames = "1.6.1"
JSON = "0.21.4"
LaTeXStrings = "1.3.1"
Measurements = "2.11.0"
Parameters = "0.12.3"
Plots = "1.39.0"
Pluto = "0.19.35"
PlutoSliderServer = "0.3.28"
PlutoUI = "0.7.54"
RecipesBase = "1.3.4"
StaticArrays = "1.7.0"
ThreadsX = "0.1.11"
YAML = "0.4.9"
ThreeBodyDecays = "0.10.5"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Corpuscles = "e78a0372-c628-4773-9c8d-eb17d149bf93"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoSliderServer = "2fc8631c-6f24-4c5b-bca7-cbb509c42db4"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"

[targets]
interactive = [
    "BenchmarkTools",
    "Corpuscles",
    "ThreadsX",
    "Plots",
    "Pluto",
    "PlutoSliderServer",
    "PlutoUI",
    "LaTeXStrings",
    "Measurements",
    "DataFrames",
]
test = ["Test"]
